version: '3.4'

services:
  php:
    image: php:7.2-fpm-alpine
    build:
      context: ./
      target: app_php
    depends_on:
      - db
    env_file:
      - .env
    # Comment out these volumes in production
    volumes:
      - ./:/srv:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./var:/srv/var:rw

  app:
    image: nginx:1.15-alpine
    build:
      context: ./
      target: app_nginx
    depends_on:
      - php
    # Comment out this volume in production
    volumes:
      - ./public:/srv/public:ro
    ports:
      - "8080:80"

  db:
    # In production, you may want to use a managed database service
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - postgresql-volume:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data! (bugged on windows)
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  # docker volume create --name=postgresql-volume
  postgresql-volume:
    external: true
